
import ClubName from "@/components/ClubName/ClubName";


import Skew2 from "@/components/HomePage/Homepage";
import Head from "next/head";
import Carousel4 from "@/components/FestCarousel/Carousel4";
import Announcement from '../components/Announcement/Announcement';
import SocietyRepresentative from '../components/SocietyRepresentative/SocietyRepresentative';
import FAQ from "@/components/FAQ/FAQ";
import Footer from '../components/Footer/Footer';
import Aboutsac from "@/components/Dean Speaks/Deanspeaks";
import Deanspeaks from "@/components/Dean Speaks/Deanspeaks";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <Skew2 />
        <Announcement />
         <Deanspeaks />
        <SocietyRepresentative />
        <FAQ />
        <Carousel4/> 
        


        <Footer />
       


        <ClubName />



        {/* <p>SAC Website</p> */}



      </main>
    </>
  );
}
