import React from "react";
import Link from "next/link";
import { useRouter } from "next/router";
import ClubName from "@/components/ClubName/ClubName";
import DeanSpeaks from "@/components/DeanSpeaks/DeanSpeaks";
import SocietyGallery from "@/components/SocietyGallery/SocietyGallery";
// import SocietyRepresentative1 from "@/components/SocietyRepresentative/SocietyContacts";
import { socData } from "../index.jsx";
import Head from "next/head.js";
import clubData from "../../../data/data.js";
import AboutNITR from "@/components/AboutPage/AboutNITR.js";

// import clubData from "../../../data/data.js";

export default function soc() {
  const router = useRouter();
  const { socID } = router.query;
  // console.log(socID);

  let backImg;
  let vcimg1;
  let vcimg2;
  if (socID == "Film and Music Society") {
    backImg =
      "https://res.cloudinary.com/dlru9kd0x/image/upload/v1679168254/new%20societies/film1_atasq9.png";
    vcimg1 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
    vcimg2 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
  } else if (socID == "Technical Society") {
    backImg =
      "https://res.cloudinary.com/dlru9kd0x/image/upload/v1679168250/new%20societies/technical1_lciid6.png";
    vcimg1 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
    vcimg2 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
  } else if (socID == "Literary and Cultural Society") {
    backImg =
      "https://res.cloudinary.com/dlru9kd0x/image/upload/v1679168258/new%20societies/lcs_2_xwljvb.png";
    vcimg1 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
    vcimg2 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
  } else {
    backImg =
      "https://res.cloudinary.com/dlru9kd0x/image/upload/v1679168252/new%20societies/sport_f8whgf.png";
    vcimg1 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
    vcimg2 =
      "https://res.cloudinary.com/de2s0mcjo/image/upload/v1697660892/manavatar_z7rrut_n5fnbm.jpg";
  }

  let socDescription = "";
  for (let index = 0; index < 4; index++) {
    if (socData[index].name == socID)
      socDescription = socData[index].description;
  }
  let socimage = "";
  for (let index = 0; index < 4; index++) {
    if (socData[index].name == socID) socimage = socData[index].aboutImg;
  }
  return (
    <>
      <Head>
        <title>Societies, NIT Rourkela</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        {/* *********** Meta SEO***********  */}
        <meta
          property="og:title"
          content="SAC NITR,Explore the plethora of thrilling events, exciting
              fests, diverse clubs and other activities in the
            beautiful campus of NIT Rourkela."
        />
        <meta
          name="keywords"
          content="sacnitr,sacnitrkl,sacnitrourkela, sac, club nitr, club, clubnitr, clubnitrkl, nitr,nitrkl,nitrourkela,nit,rourkela,nit rourkela,societies nitrkl,societiesnitrkl"
        />
        <meta
          name="description"
          content="Official Website of SAC NIT Rourkela"
        />
        {/* *********** Meta Facebook SEO***********  */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.sacnitr.com/" />
        <meta
          property="og:image"
          content="https://www.vriddhinitr.com/_next/static/media/logoBranding.00987fe3.png"
        />
        <meta property="og:image:width" content="806" />
        <meta property="og:image:height" content="280" />{" "}
        <meta name="description" content="sac 2021" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div
        className="w-[100vw] h-[100vh] bg-cover  "
        style={{
          backgroundImage: `url(${backImg})`,
        }}
      >
        <div
          className="absolute top-0 left-0 right-0 bottom-0 bg-black "
          style={{ opacity: "0.4" }}
        ></div>
        <div className="   bg-no-repeat w-full bg-cover bg-center min-h-screen">
          <div className=" w-full bg-cover bg-center min-h-screen">
            <div className="flex justify-center items-center min-h-screen">
              <div className=" text-center tracking-wide text-6xl font-bold  text-white  saturate-100 bg-cover top-0 left-0 ">
                {socID}
                <p className="  pt-10 md:text-2xl lg:text-xl text-sm   font-semibold tracking-wide mx-4 ">
                  THE TECHNICAL SOCIETY OF STUDENT ACTIVITY CENTRE, NIT
                  <br />
                  ROURKELA IS PROUD TO PRESENT ITS WORKING AND
                  <br />
                  ENTOURAGE TO ALL THE TECHNOCRATS AND INNOVATORS OF
                  <br />
                  MODERN ERA.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <DeanSpeaks
        data={`About ${socID}`}
        description={socDescription}
        image={socimage}
      />
      {/* <SocietyRepresentative1 /> */}
      <AboutNITR
        data="Vice President Speaks"
        img={`${vcimg1}`}
        description="It is a privilege for me to have assumed the position of Vice President, Technical Society of Students Activity Centre, NIT Rourkela, on 3rd July 2023. It gives me immense pleasure to say that the Students Activity Centre is getting its own website after a long drawn effort. Not only the NITian community but beyond, will now be updated with the facts and updates of mesmerizing events of the students’ societies. I would like to thank all the members involved in successfully putting up their collaborative efforts in successfully bringing up the official website."
      />
      <DeanSpeaks
        data="Vice President Speaks"
        image={`${vcimg2}`}
        description="It is a privilege for me to have assumed the position of Vice President, Technical Society of Students Activity Centre, NIT Rourkela, on 3rd July 2023. It gives me immense pleasure to say that the Students Activity Centre is getting its own website after a long drawn effort. Not only the NITian community but beyond, will now be updated with the facts and updates of mesmerizing events of the students’ societies. I would like to thank all the members involved in successfully putting up their collaborative efforts in successfully bringing up the official website."
      />

      <ClubName socName={socID} />

      <SocietyGallery title={socID} />
    </>
  );
}

export async function getStaticPaths() {
  const socName = socData;

  const allPaths = socName.map((soc) => {
    return {
      params: {
        socID: soc.name.toString(),
      },
    };
  });

  return {
    paths: allPaths,
    fallback: false,
  };
}

export function getStaticProps({ params }) {
  const clubName = clubData;
  // console.log(params);
  const data = clubName.filter((club) => {
    return club.clubSociety == params.socID;
  });

  return {
    props: {
      data,
    },
  };
}
