import React from 'react'
import Link from 'next/link'
import {useRouter}  from 'next/router';
import ClubName from '@/components/ClubName/ClubName';
import DeanSpeaks from '@/components/DeanSpeaks/DeanSpeaks';
import SocietyGallery from '@/components/SocietyGallery/SocietyGallery';
import SocietyRepresentative from '@/components/SocietyRepresentative/SocietyRepresentative';
import {socData} from '../index.jsx'
import Head from 'next/head.js';
import clubData from '../../../data/data.js';

// import clubData from "../../../data/data.js";

export default function soc() {
  const router = useRouter();
  const { socID } = router.query;
  // console.log(socID);
  
  return (
    <>
     <Head>
      <title>Societies, NIT Rourkela</title>
      {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
      <link rel="icon" href="/favicon.ico" />
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      {/* *********** Meta SEO***********  */}
      <meta
        property="og:title"
        content="SAC NITR,Explore the plethora of thrilling events, exciting
              fests, diverse clubs and other activities in the
            beautiful campus of NIT Rourkela."
      />
      <meta
        name="keywords"
        content="sacnitr,sacnitrkl,sacnitrourkela, sac, club nitr, club, clubnitr, clubnitrkl, nitr,nitrkl,nitrourkela,nit,rourkela,nit rourkela,societies nitrkl,societiesnitrkl"
      />
      <meta name="description" content="Official Website of SAC NIT Rourkela" />
      {/* *********** Meta Facebook SEO***********  */}
      <meta property="og:type" content="website" />
      <meta property="og:url" content="https://www.sacnitr.com/" />
      <meta
        property="og:image"
        content="https://www.vriddhinitr.com/_next/static/media/logoBranding.00987fe3.png"
      />
      <meta property="og:image:width" content="806" />
      <meta property="og:image:height" content="280" />{" "}
      <meta name="description" content="sac 2021" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
      <div className="bg-[url('../public/heroimg.png')] bg-no-repeat bg-cover bg-center w-full min-h-screen overflow-x-hidden">
        <div className="  bg-gradient-to-b from-[#850101cc] to-[#8501011a] bg-no-repeat w-full bg-cover bg-center min-h-screen">
          <div className="bg-[#00000073] bg-no-repeat w-full bg-cover bg-center min-h-screen">
            <div className="flex justify-center items-center min-h-screen">
              <div className=" text-center tracking-wide text-6xl font-bold  text-white  saturate-100 bg-cover top-0 left-0 ">
                {socID} 
                <p className="  pt-10 text-xl font-semibold tracking-wide ">
                  THE TECHNICAL SOCIETY OF STUDENT ACTIVITY CENTRE, NIT
                  <br />
                  ROURKELA IS PROUD TO PRESENT ITS WORKING AND
                  <br />
                  ENTOURAGE TO ALL THE TECHNOCRATS AND INNOVATORS OF
                  <br />
                  MODERN ERA.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <DeanSpeaks data="About Technincal Society" />
      <SocietyRepresentative />

      <ClubName socName={socID} />

      <SocietyGallery title={socID} />
    </>
  );
}

export async function getStaticPaths() {
  const socName = socData;

  const allPaths = socName.map((soc) => {
    return {
      params: {
        socID: soc.name.toString(),
      },
    };
  });

  return {
    paths: allPaths,
    fallback: false,
  };
}

export function getStaticProps({ params }) {
  const clubName = clubData;
  // console.log(params);
  const data = clubName.filter((club) => {
    return club.clubSociety == params.socID;
  });

  return {
    props: {
      data,
    },
  };
}
