import ClubHero2 from "@/components/ClubHero/ClubHero2";

import { Fade } from "react-awesome-reveal";
import AboutNITR from "@/components/AboutPage/AboutNITR";
import SocietyGallery from "../../components/SocietyGallery/SocietyGallery";

import React from "react";
import Footer from "@/components/Footer/Footer";
import Announcement from "@/components/Announcement/Announcement";
import AboutPage from "@/components/AboutPage/AboutPage";
import Image from "next/image";
import DeanSpeaks from "@/components/DeanSpeaks/DeanSpeaks";
import dean from "../../public/dean.jpg";
import SocietyRepresentative from "@/components/SocietyRepresentative/SocietyRepresentative";
import Head from "next/head";

export default function Club() {
  return (
    <div>
      <Head>
        <title>Societies, NIT Rourkela</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        {/* *********** Meta SEO***********  */}
        <meta
          property="og:title"
          content="SAC NITR,Explore the plethora of thrilling events, exciting
              fests, diverse clubs and other activities in the
            beautiful campus of NIT Rourkela."
        />
        <meta
          name="keywords"
          content="sacnitr,sacnitrkl,sacnitrourkela, sac, club nitr, club, clubnitr, clubnitrkl, nitr,nitrkl,nitrourkela,nit,rourkela,nit rourkela,societies nitrkl,societiesnitrkl"
        />
        <meta
          name="description"
          content="Official Website of SAC NIT Rourkela"
        />
        {/* *********** Meta Facebook SEO***********  */}
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.sacnitr.com/" />
        <meta
          property="og:image"
          content="https://www.vriddhinitr.com/_next/static/media/logoBranding.00987fe3.png"
        />
        <meta property="og:image:width" content="806" />
        <meta property="og:image:height" content="280" />{" "}
        <meta name="description" content="sac 2021" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ClubHero2 />
      <DeanSpeaks data={`About Webwiz`} />
      <SocietyRepresentative data={`Club representatives`} />
      {/* <ClubName/> */}
      <SocietyGallery />

      {/* <Footer/> */}
    </div>
  );
}
